language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

env:
  matrix:
    - COMPOSER_PARAM="update --prefer-source --prefer-lowest"
    - COMPOSER_PARAM="update --prefer-source"

matrix:
  allow_failures:
    - php: nightly

before_script:
    - composer selfupdate
    - composer $COMPOSER_PARAM

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
